-- Initial schema from supabase/schema.sql
-- Profiles and Appointments with RLS and guards

-- Ensure profiles table exists
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade
);

-- Bring table to expected shape
alter table public.profiles add column if not exists role text;
alter table public.profiles add column if not exists doctor_slug text;
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists phone text;
alter table public.profiles add column if not exists created_at timestamptz default now();
alter table public.profiles add column if not exists updated_at timestamptz default now();

update public.profiles set role = 'patient' where role is null;
alter table public.profiles alter column role set default 'patient';
alter table public.profiles alter column role set not null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'profiles_role_check') then
    alter table public.profiles add constraint profiles_role_check check (role in ('patient','doctor','admin'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'profiles_doctor_slug_key') then
    alter table public.profiles add constraint profiles_doctor_slug_key unique (doctor_slug);
  end if;
end $$;

-- Helper
create or replace function public.is_admin() returns boolean as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$ language sql stable;

-- RLS for profiles
alter table public.profiles enable row level security;

drop policy if exists "Read own profile" on public.profiles;
create policy "Read own profile" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "Update own profile" on public.profiles;
create policy "Update own profile" on public.profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);

drop policy if exists "Admin can read all profiles" on public.profiles;
create policy "Admin can read all profiles" on public.profiles
  for select using (public.is_admin());

drop policy if exists "Admin can update profiles" on public.profiles;
create policy "Admin can update profiles" on public.profiles
  for update using (public.is_admin())
  with check (public.is_admin());

-- Prevent non-admin role changes
create or replace function public.profiles_no_role_change()
returns trigger as $$
begin
  if new.role is distinct from old.role and not public.is_admin() then
    raise exception 'Only admins can change role';
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_profiles_no_role_change on public.profiles;
create trigger trg_profiles_no_role_change
  before update on public.profiles
  for each row execute function public.profiles_no_role_change();

-- Appointments
create table if not exists public.appointments (
  id bigint generated by default as identity primary key,
  patient_id uuid not null references auth.users(id) on delete cascade,
  doctor_identifier text not null references public.profiles(doctor_slug) on update cascade on delete restrict,
  appt_date date not null,
  appt_time text not null,
  appt_type text not null default 'video',
  status text not null default 'pending',
  created_at timestamptz default now()
);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'appointments_appt_type_check') then
    alter table public.appointments add constraint appointments_appt_type_check check (appt_type in ('video','in_clinic'));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'appointments_status_check') then
    alter table public.appointments add constraint appointments_status_check check (status in ('pending','accepted','declined','cancelled'));
  end if;
end $$;

alter table public.appointments enable row level security;

-- Patients: insert and view own
 drop policy if exists "Patient can insert own appointments" on public.appointments;
create policy "Patient can insert own appointments" on public.appointments
  for insert with check (auth.uid() = patient_id);

 drop policy if exists "Patient can view own appointments" on public.appointments;
create policy "Patient can view own appointments" on public.appointments
  for select using (auth.uid() = patient_id);

-- Doctors: view and update status for their appointments (by doctor_slug)
 drop policy if exists "Doctor can view their appointments" on public.appointments;
create policy "Doctor can view their appointments" on public.appointments
  for select using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role = 'doctor'
        and p.doctor_slug = public.appointments.doctor_identifier
    )
  );

 drop policy if exists "Doctor can update their appointments" on public.appointments;
create policy "Doctor can update their appointments" on public.appointments
  for update using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role = 'doctor'
        and p.doctor_slug = public.appointments.doctor_identifier
    )
  ) with check (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid()
        and p.role = 'doctor'
        and p.doctor_slug = public.appointments.doctor_identifier
    )
  );

-- Admin: full access
 drop policy if exists "Admin can read appointments" on public.appointments;
create policy "Admin can read appointments" on public.appointments
  for select using (public.is_admin());

 drop policy if exists "Admin can update appointments" on public.appointments;
create policy "Admin can update appointments" on public.appointments
  for update using (public.is_admin()) with check (public.is_admin());

-- Optional guard: doctors may only change status
create or replace function public.appointments_doctor_update_guard()
returns trigger as $$
begin
  -- allow admins without restriction
  if public.is_admin() then
    return new;
  end if;

  -- if doctor is updating (matched by policy), restrict to status only
  if (
    (new.patient_id is distinct from old.patient_id) or
    (new.doctor_identifier is distinct from old.doctor_identifier) or
    (new.appt_date is distinct from old.appt_date) or
    (new.appt_time is distinct from old.appt_time) or
    (new.appt_type is distinct from old.appt_type)
  ) then
    raise exception 'Doctors may only update appointment status';
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists trg_appointments_doctor_update_guard on public.appointments;
create trigger trg_appointments_doctor_update_guard
  before update on public.appointments
  for each row execute function public.appointments_doctor_update_guard();


