-- Chat feature: conversations and messages tables

-- Conversations table
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references auth.users(id) on delete cascade,
  doctor_id uuid not null references auth.users(id) on delete cascade,
  appointment_id bigint references public.appointments(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Unique constraints: one conversation per appointment, or one general conversation per patient-doctor pair
create unique index if not exists conversations_appointment_unique 
  on public.conversations(patient_id, doctor_id, appointment_id) 
  where appointment_id is not null;

create unique index if not exists conversations_general_unique 
  on public.conversations(patient_id, doctor_id) 
  where appointment_id is null;

-- Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  content text,
  attachment_url text,
  attachment_type text check (attachment_type in ('image', 'document')),
  attachment_name text,
  created_at timestamptz default now(),
  read_at timestamptz
);

-- Indexes for performance
create index if not exists messages_conversation_id_idx on public.messages(conversation_id);
create index if not exists messages_sender_id_idx on public.messages(sender_id);
create index if not exists messages_created_at_idx on public.messages(created_at);
create index if not exists conversations_patient_id_idx on public.conversations(patient_id);
create index if not exists conversations_doctor_id_idx on public.conversations(doctor_id);
create index if not exists conversations_updated_at_idx on public.conversations(updated_at);

-- Function to update conversations.updated_at when a message is inserted
create or replace function public.update_conversation_updated_at()
returns trigger as $$
begin
  update public.conversations
  set updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_update_conversation_updated_at on public.messages;
create trigger trg_update_conversation_updated_at
  after insert on public.messages
  for each row execute function public.update_conversation_updated_at();

-- Enable RLS
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- RLS Policies for conversations
-- Patients can read/create conversations where they are the patient
drop policy if exists "Patients can read own conversations" on public.conversations;
create policy "Patients can read own conversations" on public.conversations
  for select using (patient_id = auth.uid());

drop policy if exists "Patients can create own conversations" on public.conversations;
create policy "Patients can create own conversations" on public.conversations
  for insert with check (patient_id = auth.uid());

-- Doctors can read/create conversations where they are the doctor
drop policy if exists "Doctors can read own conversations" on public.conversations;
create policy "Doctors can read own conversations" on public.conversations
  for select using (doctor_id = auth.uid());

drop policy if exists "Doctors can create own conversations" on public.conversations;
create policy "Doctors can create own conversations" on public.conversations
  for insert with check (doctor_id = auth.uid());

-- RLS Policies for messages
-- Users can insert messages into conversations they're part of
drop policy if exists "Users can insert messages in own conversations" on public.messages;
create policy "Users can insert messages in own conversations" on public.messages
  for insert with check (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (c.patient_id = auth.uid() or c.doctor_id = auth.uid())
        and sender_id = auth.uid()
    )
  );

-- Users can read messages from conversations they're part of
drop policy if exists "Users can read messages in own conversations" on public.messages;
create policy "Users can read messages in own conversations" on public.messages
  for select using (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (c.patient_id = auth.uid() or c.doctor_id = auth.uid())
    )
  );

-- Users can update read_at for messages they received (not sent)
drop policy if exists "Users can update read_at for received messages" on public.messages;
create policy "Users can update read_at for received messages" on public.messages
  for update using (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (c.patient_id = auth.uid() or c.doctor_id = auth.uid())
        and sender_id != auth.uid()
    )
  )
  with check (
    exists (
      select 1 from public.conversations c
      where c.id = conversation_id
        and (c.patient_id = auth.uid() or c.doctor_id = auth.uid())
        and sender_id != auth.uid()
    )
  );

